-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgRrrngVnAd99hp6oz
iH1vxfHtw5JxHmjSdrneCDNVmbqgCgYIKoZIzj0DAQehRANCAAQkikF/6GiRPQiu
Sl6TlCx7fr5q5P8aPCgklHhN5MbX1L6/qdCIMsaiL5t6i91rMqlUCeD3uL7aBckX
kEeB/HBQ
-----END PRIVATE KEY-----